Main/Main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Productos.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if  settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/Productos/urls.py
from django.conf import settings
from django.urls import include, path
from . import views, views_carrito, controlador_sesion
from django.conf.urls.static import static
from .views import  ListaPedidos
urlpatterns = [
  path('', views.home, name= 'home'),
  path('shop', views.shop, name='shop'),
  path('crear_pedido/', views.crear_pedido, name='crear_pedido'),
  path('pedido/<uuid:pedido_id>/', views.vista_pedido, name='vista_pedido'),    
  path('carrito/', views_carrito.carrito, name='carrito'),
  path('carrito/agregar/<int:producto_id>/', views_carrito.agregar_al_carrito, name='agregar_al_carrito'),
  path('eliminar_del_carrito/<int:producto_id>/', views_carrito.eliminar_del_carrito, name='eliminar_del_carrito'),
  path('carrito/eliminar/', views_carrito.eliminar_carrito, name='eliminar_carrito'),
  path('carrito/aumentar/<int:detalle_id>/', views_carrito.aumentar_cantidad, name='aumentar_cantidad'),
  path('carrito/disminuir/<int:detalle_id>/', views_carrito.disminuir_cantidad, name='disminuir_cantidad'),
  path('obtener-numero-productos-en-carrito/', views_carrito.obtener_numero_productos_en_carrito, name='obtener_numero_productos_en_carrito'),
  path('buscar/', views_carrito.buscar_productos, name='buscar_productos'),
  path("registro", controlador_sesion.registro, name="registro"),
  path("loginn/", controlador_sesion.loginn, name="loginn"),
  path('logout', controlador_sesion.cerrar, name='logout'),
  path('<int:id>', views.detalles_producto , name='detalles'),
  path('pedidos/', ListaPedidos.as_view(), name='lista_pedidos'),
  path('base', views.base_view, name='base'),

]  

Main/Productos/models.py
from pyexpat import model
from turtle import mode
from django.db import models
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from sqlalchemy import false, true
from autoslug import AutoSlugField
import uuid

class SliderImage(models.Model):
    image = models.ImageField(upload_to='slider_images', null=False)
    title = models.CharField(max_length=100, null= True)
    description = models.TextField()

    def __str__(self):
        return self.title
   
class Categoria(models.Model):
    id =  models.AutoField(primary_key=True)
    nombre =  models.CharField(max_length=40, verbose_name = "Nombre de la categoria")

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=40, verbose_name="Nombre del Producto", db_index=True)
    categoria = models.ForeignKey(Categoria, on_delete= models.CASCADE, null=False)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField( upload_to='imagenes/', verbose_name="Imagen", null=True, blank=True)
    descripcion = models.TextField(null=True)
    especial = models.BooleanField(default=False, verbose_name="Producto especial")
    disponible = models.BooleanField(default=False, verbose_name="Disponibilidad del producto")

    def __str__(self):
      return self.nombre
    
    def delete(self, using=None, keep_parents=False):
        self.imagen.storage.delete(self.imagen.name)
        super().delete(using=using, keep_parents=keep_parents)

class Carrito(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField('Producto', through='DetalleCarrito')
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def calcular_total(self):
        self.total = sum(detalle.precio_total() for detalle in self.detallecarrito_set.all())
        self.save()


class DetalleCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def precio_total(self):
        return self.producto.precio * self.cantidad



class Metodos_pago(models.Model):
    nombre =  models.CharField(max_length=100)
   
    def __str__(self):
        return self.nombre

class Pedido(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    metodo_pago = models.ForeignKey(Metodos_pago, on_delete=models.CASCADE, null=True)
    descripcion = models.CharField(null=True, max_length=300, blank=True)

class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    precio_total = models.DecimalField(max_digits=10, decimal_places=2)

class informacion(models.Model):
    titulo =  models.CharField(max_length=40, null=True)
    descripcion = models.TextField(null=True)
    direccion = models.TextField(null=True)
    numero = models.TextField(null=True)
    def __str__(self):
        return self.titulo

Main/Productos/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth import authenticate
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from Productos.models import Pedido
from django.contrib.auth.forms import AuthenticationForm



class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['nombre', 'direccion', 'telefono', 'metodo_pago', 'descripcion']


class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )

class CustomAuthenticationForm(AuthenticationForm):
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if user is None:
                raise forms.ValidationError("Usuario o contraseña incorrectos")
            elif not user.is_active:
                raise forms.ValidationError("Esta cuenta está desactivada")
            # Puedes añadir más validaciones aquí según tus requisitos
        return self.cleaned_data

Main/Productos/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import DetallePedido, Pedido, SliderImage, informacion
from .models import Producto, DetalleCarrito, Categoria
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.core.cache import cache
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from Productos.forms import PedidoForm
from .models import Carrito, DetallePedido, Pedido, Producto, DetalleCarrito
from django.template.defaultfilters import floatformat
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from .models import Pedido

def home(request):
    imagen = SliderImage.objects.all()
    productos_especiales = Producto.objects.filter(especial=True)[:10]
    categoria = Categoria.objects.all()
    return render(request, 'principal/home.html', {'imagen': imagen, 'productos': productos_especiales, 'categoria': categoria})



def shop(request):
    categorias = Categoria.objects.all()
    categoria_seleccionada = None

    # Obtener productos de la caché o realizar la consulta si no está en caché
    productos_cache_key = 'productos_tienda'
    productos = cache.get(productos_cache_key)
    if not productos:
        productos = Producto.objects.all()
        cache.set(productos_cache_key, productos)

    if 'categoria_id' in request.GET:
        categoria_id = request.GET['categoria_id']
        if categoria_id:
            categoria_seleccionada = get_object_or_404(Categoria, id=categoria_id)
            productos = productos.filter(categoria=categoria_seleccionada)

    return render(request, 'principal/shop.html', {'categorias': categorias, 'productos': productos, 'categoria_seleccionada': categoria_seleccionada})




def crear_pedido(request):
    try:
        carrito = Carrito.objects.get(user=request.user)
    except Carrito.DoesNotExist:
        return JsonResponse(
            {
                "mensaje": "Tu carrito está vacío. Por favor, agrega productos antes de proceder al pedido."
            }
        )

    if carrito.productos.count() == 0:
        return JsonResponse(
            {
                "mensaje": "Tu carrito está vacío. Por favor, agrega productos antes de proceder al pedido."
            }
        )

    if request.method == "POST":
        form = PedidoForm(request.POST)
        if form.is_valid():
            pedido = form.save(commit=False)
            pedido.user = request.user  # Asignar el usuario al pedido
            pedido.save()
            for detalle_carrito in carrito.detallecarrito_set.all():
                DetallePedido.objects.create(
                    pedido=pedido,
                    producto=detalle_carrito.producto,
                    cantidad=detalle_carrito.cantidad,
                    precio_unitario=detalle_carrito.producto.precio,
                    precio_total=detalle_carrito.precio_total(),
                )

            carrito.productos.clear()
            carrito.total = 0
            carrito.save()
            return redirect("vista_pedido", pedido_id=pedido.id)
    else:
        form = PedidoForm()

    return render(request, "principal/pedido.html", {"form": form})



def detalles_producto(request, id):
    producto = get_object_or_404(Producto, pk=id)

    # Obtener productos relacionados de la caché o realizar la consulta si no está en caché
    productos_relacionados_cache_key = f'productos_relacionados_{producto.categoria.id}'
    productos_relacionados = cache.get(productos_relacionados_cache_key)
    if not productos_relacionados:
        productos_relacionados = Producto.objects.filter(categoria=producto.categoria).exclude(id=producto.id).order_by('?')[:8]
        cache.set(productos_relacionados_cache_key, productos_relacionados)

    return render(request, 'principal/detalles.html', {'producto': producto, 'productos_relacionados': productos_relacionados})



# Verificar si el usuario es administrador
def es_admin(user):
    return user.is_staff

@login_required
def vista_pedido(request, pedido_id):
    # Verificar si el usuario es administrador
    if request.user.is_staff:
        pedido = get_object_or_404(Pedido, id=pedido_id)
    else:
        pedido = get_object_or_404(Pedido, id=pedido_id, user=request.user)
    
    detalles = DetallePedido.objects.filter(pedido=pedido)
    total_pedido = sum(detalle.precio_total for detalle in detalles)
    return render(
        request,
        "principal/correcto.html",
        {"pedido": pedido, "detalles": detalles, "total_pedido": total_pedido},
    )




class ListaPedidos(LoginRequiredMixin, ListView):
    model = Pedido
    template_name = 'principal/admin/Pedidos_hechos.html'
    context_object_name = 'pedidos'

    def get_queryset(self):
        # Si el usuario es un administrador, mostrar todos los pedidos
        if self.request.user.is_staff:
            return Pedido.objects.all().order_by('-fecha_pedido')
        # Si el usuario no es un administrador, mostrar solo sus propios pedidos
        else:
            return Pedido.objects.filter(user=self.request.user).order_by('-fecha_pedido')



def base_view(request):
    # Consulta el modelo informacion
    info = informacion.objects.first()  # Suponiendo que solo hay un registro
    return render(request, 'base.html', {'info': info})

Main/Productos/templates/principal/busqueda.html
{% extends "base.html" %}
{% load static %}
{% load my_filters %}
{% block titulo %} Home {% endblock %}
{% block contenido %}
    <link rel="stylesheet" href="{% static 'css/home_tarjetas.css' %}?v=1">
 
    <div class="posicion">  
        <section class="products">
            <div class= "container2">
             
                <div class="select">
                <select name="categoria" id="categoria">
                    <option value="">Categorias</option>
                    {% for categoria in categorias %}
                        <option value="{{ categoria.id }}" {% if categoria_seleccionada == categoria %}selected{% endif %}>{{ categoria.nombre }}</option>
                    {% endfor %}
                </select>
              </div>
            </div> 
            <br>
            <h4 class="product-title" style="text-align: center; justify-content: center; display: flex;">Resultados de busqueda para: {{ query }}</h4>
            <div class="all-products">
                {% for producto in productos %}
                    <div class="product">
                        <img src="{{ producto.imagen.url }}" alt="" loading="lazy">
    
                        <div class="product-info">
                            <h4 class="product-title">{{ producto.nombre }}</h4>
                            <p class="product-price">$  {{ producto.precio }}</p>
                            <h5 class="product-title">categoria: {{ producto.categoria }}</h5>
                            <br>
                            <form class="agregar-producto-form" data-producto-id="{{ producto.id }}">
                                {% csrf_token %}
                                <input type="hidden" name="producto_id" value="{{ producto.id }}">
                                <button type="button" class="button-50 agregar-al-carrito">Agregar al carrito</button>
                            </form>
                            
                            <a class="button-50" href="{% url 'detalles' producto.id %}">Detalles</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>
    
    <script>
        document.getElementById('categoria').addEventListener('change', function() {
            var categoriaId = this.value;
            window.location.href = "{% url 'shop' %}?categoria_id=" + categoriaId;
        });
    </script>

{% endblock %}

Main/Productos/templates/principal/carrito.html
{% extends "base.html" %}
{% load static %}
{% load my_filters %}
{% block titulo %} Carro {% endblock %}

{% block contenido %}
<link rel="stylesheet" href="{% static 'css/carrito.css' %}?v=1">


<br>
<br>
<br>
<br>
<style>
    .carrito-list {
    list-style: none;
    padding: 0;
    margin: 0;
}

.detalle-carrito {
    border-bottom: 1px solid #ccc; /* Agrega una línea divisoria entre cada elemento */
    padding: 20px 0; /* Espacio entre cada elemento */
}

/* Estilos adicionales para los elementos del carrito */
.detalle-carrito:last-child {
    border-bottom: none; /* Quita la línea divisoria en el último elemento */
}

</style>
<section class="carrito-container">
    <div class="carrito-header">
        <h1 class="text-xl font-bold text-gray-900">Carrito de compras</h1>
    </div>

    <div class="carrito-items">
        <ul class="carrito-list">
            <!-- Itera sobre los elementos del carrito -->
            {% for detalle in carrito.detallecarrito_set.all %}
            <li class="detalle-carrito" data-detalle-id="{{ detalle.id }}">
                <img src="{{ detalle.producto.imagen.url }}" alt="{{ detalle.producto.nombre }}" class="detalle-imagen">
                <div class="detalle-info">
                    <h3 class="detalle-nombre">{{ detalle.producto.nombre }}</h3>
                    <p class="detalle-descripcion">{{ detalle.producto.descripcion }}</p>
                </div>
                <div class="detalle-acciones">
                    <form action="{% url 'aumentar_cantidad' detalle.id %}" method="post" class="cantidad-form" data-detalle-id="{{ detalle.id }}">
                        {% csrf_token %}
                        <button type="submit" class="btn-accion">
                            <i class="ri-add-line"></i>
                        </button>
                    </form>
                    <span class="cantidad">{{ detalle.cantidad }}</span>
                    <form action="{% url 'disminuir_cantidad' detalle.id %}" method="post" class="cantidad-form" data-detalle-id="{{ detalle.id }}">
                        {% csrf_token %}
                        <button type="submit" class="btn-accion">
                            <i class="ri-subtract-line"></i>
                        </button>
                    </form>
                    <span class="precio-total"> {{ detalle.precio_total|formato_moneda }}</span>
                    
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="carrito-footer">
        <dl class="text-sm text-gray-700">
            <div class="total">
                <dt>Precio total:</dt>
                <dd id="total-neto">{{ carrito.total|formato_moneda }}</dd>
            </div>
        </dl>

        <div class="botones">
            <a href="{% url 'home' %}" class="rounded bg-gray-700">Back to shop</a>
            <a href="{% url 'eliminar_carrito' %}" class="rounded bg-gray-700">Vaciar el carro</a>
            <a href="{% url 'crear_pedido' %}" class="rounded bg-gray-700" onclick="return irAlPedido();">Ir al Pedido</a>
        </div>
    </div>
</section>


<script src="{% static 'js/carrito.js' %}"></script>
<script>
    function irAlPedido() {
        // Verificar si el carrito está vacío
        if ({{ carrito.productos.count }} === 0) {
                Swal.fire({
            icon: 'warning',
            title: 'Tu carrito está vacío',
            text: 'Por favor, agrega productos antes de proceder al pedido.',
            showConfirmButton: false,
            timer: 3000
        });
            return false; // Detener la acción del enlace
        }
        return true; // Permitir la acción del enlace si el carrito no está vacío
    }
</script>

{% endblock %}

Main/Productos/templates/principal/correcto.html
{% load static %}
{% load my_filters %}
{% block titulo %}  {% endblock %}

{% block contenido %}
<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 

<br>
<br> 
<div class="container mx-auto p-4">
    <h1 class="text-3xl font-bold mb-4">Detalle del Pedido</h1>

    <div class="mb-8">
        <h2 class="text-xl font-semibold mb-2">Información del Cliente:</h2>
        <div class="grid grid-cols-2 gap-4">
            <p><strong>Nombre:</strong> {{ pedido.nombre }}</p>
            {% if pedido.descripcion %}
                <p><strong>Descripción:</strong> {{ pedido.descripcion }}</p>
            {% else %}
                <p><strong>Descripción:</strong> No hay descripción</p>
            {% endif %}
            <p><strong>Dirección:</strong> {{ pedido.direccion }}</p>
            <p><strong>Teléfono:</strong> {{ pedido.telefono }}</p>
            <p><strong>Método de pago:</strong> {{ pedido.metodo_pago }}</p>
            <p><strong>Fecha de pedido:</strong> {{ pedido.fecha_pedido }}</p>

        </div>
    </div>


    <div class="mb-8">
        <h2 class="text-xl font-semibold mb-2">Productos:</h2>
        <div class="overflow-x-auto">
            <table class="table-auto w-full">
                <thead>
                    <tr>
                        <th class="px-4 py-2">Producto</th>
                        <th class="px-4 py-2">Cantidad</th>
                        <th class="px-4 py-2">Precio Unitario</th>
                        <th class="px-4 py-2">Precio Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for detalle in detalles %}
                    <tr>
                        <td class="border px-4 py-2">{{ detalle.producto.nombre }}</td>
                        <td class="border px-4 py-2">{{ detalle.cantidad }}</td>
                        <td class="border px-4 py-2">{{ detalle.precio_unitario|formato_moneda }}</td>
                        <td class="border px-4 py-2">{{ detalle.precio_total|formato_moneda }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="mb-8">
        <h2 class="text-xl font-semibold mb-2">Total del Pedido: {{ total_pedido|formato_moneda }}</h2>
    </div>

    
    <a href="{% url 'home' %}" class="button-35" role="button">Volver al inicio</a>
    <br>
    <br>
    {% if request.user.is_authenticated  %}
     <a  type="button" href="{% url 'lista_pedidos' %}" class="button-35" role="button">Volver a pedidos</a>  
    {% endif %}
</div>

<!-- HTML !-->


<style>    

/* CSS */
.button-35 {
  align-items: center;
  background-color: #fff;
  border-radius: 12px;
  box-shadow: transparent 0 0 0 3px,rgba(18, 18, 18, .1) 0 6px 20px;
  box-sizing: border-box;
  color: #121212;
  cursor: pointer;
  display: inline-flex;
  flex: 1 1 auto;
  font-family: Inter,sans-serif;
  font-size: 1.2rem;
  font-weight: 700;
  justify-content: center;
  line-height: 1;
  margin: 0;
  outline: none;
  padding: 1rem 1.2rem;
  text-align: center;
  text-decoration: none;
  transition: box-shadow .2s,-webkit-box-shadow .2s;
  white-space: nowrap;
  border: 0;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
}

.button-35:hover {
  box-shadow: #121212 0 0 0 3px, transparent 0 0 0 0;
}

</style>


{% endblock %}

Main/Productos/templates/principal/detalles.html
{% extends "base.html" %}
{% load static %}
{% load my_filters %}
{% block titulo %} Home {% endblock %}
{% block contenido %}

<link rel="stylesheet" href="{% static 'css/boots.css' %}">
<link rel="stylesheet" href="{% static 'css/home_tarjetas.css' %}?v=1">
<br>
<br>
<br>
<br>


    <div class="card-wrapper">
        <div class="card">
            <div class="product-imgs">
                <div class="img-display">
                    <div class="img-showcase">
                        <img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}">
                    </div>
                </div>
            </div>
            <div class="product-content">
                <h2 class="product-title">{{ producto.nombre }}</h2>
                <div class="product-detail">
                    
                    <ul>
                        <h2>precio: <p>{{producto.precio|formato_moneda}}</p></h3>
                        {% if producto.disponible %}
                            <li><strong>Disponibilidad:</strong> <span>En stock</span></li>
                        {% else %}
                            <li><strong>Disponibilidad:</strong> <span style="color: red;">No disponible</span></li>
                        {% endif %}
                        <li><strong>Categoría:</strong> <span>{{ producto.categoria }}</span></li>
                    </ul>
                    <p>{{ producto.descripcion }}</p>
                </div>
                <div class="purchase-info">
                               <form class="agregar-producto-form" data-producto-id="{{ producto.id }}">
                            {% csrf_token %}
                            <input type="hidden" name="producto_id" value="{{ producto.id }}">
                            <!-- Agregar un campo de entrada para la cantidad -->
                            <label for="cantidad">Cantidad:</label>
                            <input type="number" name="cantidad" class="cantidad" value="1" min="1">
                            <!-- <button type="button" class="bn632-hover bn25 agregar-al-carrito">Agregar al carrito</button> -->
                            <button type="button" class="button-50 agregar-al-carrito">Agregar al carrito <i class = "fas fa-shopping-cart"></i></button>
                        </form>
                </div>
            </div>
        </div>
    </div>
    

    <br>

    <section class="related-products">
        <div class="five">
            <div>Productos relacionados</div>
        </div>
    
        <div class="all-products">
            {% for producto_relacionado in productos_relacionados %}
                <div class="product">
                    <img src="{{ producto_relacionado.imagen.url }}">

                    <div class="product-info">
                        <h4 class="">{{ producto_relacionado.nombre }}</h4>
                        <h5 class="">Categoría: {{ producto_relacionado.categoria }}</h5>
                        <p class="product-price">$ {{ producto_relacionado.precio|formato_moneda }}</p>
                      
                        <form class="agregar-producto-form" data-producto-id="{{ producto.id }}">
                            {% csrf_token %}
                            <input type="hidden" name="producto_id" value="{{ producto_relacionado.id }}">
                            <button type="button" class="button-50 agregar-al-carrito">Agregar al carrito</button>
         
                        </form>
                        <a class="button-50" href="{% url 'detalles' producto_relacionado.id %}">Detalles</a>
                    </div>
           
                </div>
            {% endfor %}
        </div>
    </section>
    
{% endblock %}

Main/Productos/templates/principal/home.html
{% extends "base.html" %}
{% load static %}
{% load my_filters %}
{% block titulo %}
    Home
{% endblock %}

{% block contenido %}

    <link rel="stylesheet" href="{% static 'css/home_tarjetas.css' %}?v=1">
    <link rel="stylesheet" href="{% static 'css/header.css' %}?v=1">
  

    <div id="container-slider">
        <a href="#" onclick="fntExecuteSlide('prev');" class="arrowPrev"><i class="fas fa-chevron-circle-left"></i></a>
        <a href="#" onclick="fntExecuteSlide('next');" class="arrowNext"><i class="fas fa-chevron-circle-right"></i></a>

        <ul id="slider">
            {% for slide in imagen %}
            <li style="background-image: url('{{ slide.image.url }}'); z-index:{{ forloop.counter0 }}; opacity: {{ forloop.first|yesno:'1,0' }}"> <!-- Ajusta el estilo del slide -->
                <div class="content_slider">
                    <div>
                        <h2>{{slide.title}}</h2>
                        <p>{{slide.description}}</p>
                        <!-- <a href="#" class="btnSlider">Ver más</a> -->
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    
<br>
<br>


    <section class="products">
        <div class="five">
            <div>Productos principales</div>
        </div>

        <div class="all-products">
            {% for producto in productos %}
                <div class="product">
                    <img src="{{ producto.imagen.url }}" alt="" loading="lazy">

                    <div class="product-info">
                        <h4 class="product-title">{{producto.nombre}}</h4>
                        <h5 class="product-title">categoria: {{ producto.categoria }}</h5>
                        <p class="product-price">$  {{ producto.precio|formato_moneda }}</p>
                        <form class="agregar-producto-form" data-producto-id="{{ producto.id }}">
                            {% csrf_token %}
                            <input type="hidden" name="producto_id" value="{{ producto.id }}">                    
                            <button type="button" class="button-50 agregar-al-carrito">Agregar al carrito</button>
                        </form>
                        <a class="button-50" href="{% url 'detalles' producto.id %}">Detalles</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        
    </section>


    <script src="{% static 'js/custom.js' %}"></script>
{% endblock %}

Main/Productos/templates/principal/info.html
{% load static $}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

Main/Productos/templates/principal/pedido.html
{% extends "base.html" %}
{% load static %}
{% load my_filters %}
{% block titulo %} Pedido {% endblock %}

{% block contenido %}

<br>
<br>
<br>
<br>
<link rel="stylesheet" href="{% static 'css/form.css' %}">


    <div class="container">
        <h1>¡Compartenos tu información!</h1>
        <p>Llena los campos con tus datos para efectuar el pedido</p>  
        
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="row">
                <div class="column">
                    <label for="id_nombre">Nombre</label>
                    {{ form.nombre  }}
                    {{ form.nombre.errors }}
                </div>
                <div class="column">
                    <label for="id_direccion">Dirección</label>
                    {{ form.direccion   }}
                    {{ form.nombre.errors }}
                </div>
                <div class="column">
                    <label for="id_numero">Número de telefono</label>
                    {{ form.telefono }}
                </div>
            </div>
            <div class="row">
                <div class="column">
                    <label for="id_nombre">Metodo de pago</label>
                    {{ form.metodo_pago  }}
                    
                </div>
                <div class="column">
                    <label for="id_direccion"> Descripcion del pedido <div style="font: bold; color: red;">(No es necesario llenar este campo) </div></label>
                    {{ form.descripcion   }}
                    {{ form.nombre.errors }}
                </div>
  
            </div>

            <button class="boton" type="submit">Submit</button>
            
        </form>  
        <br>
        <div id="alerta"></div> 
    </div>

    
    

{% endblock %}